-- Active: 1693992872757@@127.0.0.1@3306@springdb
CREATE TABLE USERS(
    ID VARCHAR(8) PRIMARY KEY,
    PASSWORD VARCHAR(8),
    NAME VARCHAR(20),
    COMPANY VARCHAR(20),
    GITHUB VARCHAR(50)
);

CREATE TABLE BOARD(
SEQ INT AUTO_INCREMENT PRIMARY KEY,
CATE VARCHAR(5),
WRITERID VARCHAR(20),
CONTENT VARCHAR(2000),
REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

select * from users;
select * from board;

select * from board where cate = 'm' order by seq desc;

CREATE TABLE COMM(
SEQ INT AUTO_INCREMENT PRIMARY KEY,
CATE VARCHAR(5),
TITLE VARCHAR(200),
CONTENT VARCHAR(2000),
WRITERID VARCHAR(20),
VIEW INT DEFAULT 0,
REPLY INT DEFAULT 0,
REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

select * from COMM;
drop table COMM;

CREATE TABLE COMMREPLY(
IDX INT AUTO_INCREMENT PRIMARY KEY,
SEQ INT,
WRITERID VARCHAR(20),
CONTENT VARCHAR(2000),
REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (SEQ) REFERENCES COMM(SEQ) ON DELETE CASCADE
);

SELECT comm.*
FROM comm
JOIN commreply ON comm.seq = commreply.seq
WHERE commreply.writerId = 'lee';

drop table COMMREPLY;
select * from commreply;

select * from commreply where seq=8 order by idx desc;

CREATE TABLE STUDY(
SEQ INT AUTO_INCREMENT PRIMARY KEY,
CATE VARCHAR(20),
TITLE VARCHAR(200),
GOAL VARCHAR(1000),
CONTENT VARCHAR(2000),
WRITERID VARCHAR(20),
REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

drop table STUDY;
select * from study;

CREATE TABLE CHAT(
IDX INT AUTO_INCREMENT PRIMARY KEY,
SEQ INT,
WRITERID VARCHAR(20),
CONTENT VARCHAR(2000),
REGDATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

drop table chat;
select * from chat;
select * from chat where seq=10 order by idx;

DELETE FROM chat WHERE seq = 11;
